#!/bin/bash

dir=$(cd `dirname $0`; pwd)

#############################生成证书

# 运行容器
docker run --net=host  \
	-v ${dir}/elastic/instances.yml:/usr/share/elasticsearch/config/certificates/instances.yml \
	-v ${dir}/elastic/certs:/usr/share/elasticsearch/config/certificates/certs \
	15918793994/elasticsearch:6.2.4 bash -c '
	    cd /usr/share/elasticsearch
        if [[ ! -d config/certificates/certs ]]; then
          mkdir config/certificates/certs -p;
        fi;
        if [[ ! -f /local/certs/bundle.zip ]]; then
          bin/x-pack/certgen --silent --in config/certificates/instances.yml --out config/certificates/certs/bundle.zip;
            unzip config/certificates/certs/bundle.zip -d config/certificates/certs;
        fi;
        chgrp -R 0 config/certificates/certs
      '