#!/bin/bash

dir=$(cd `dirname $0`; pwd)

#############################启动filebeat
# 拉取证书
rm -rf ${dir}/filebeat/certs
ln -s ${dir}/elastic/certs ${dir}/filebeat/certs

# 删除运行中的容器
docker rm $(docker ps -a| grep "filebeat" |cut -d " " -f 1) -f

# 修改项目权限
chown 1000:1000 -R ${dir}/filebeat

# 创建容器hosts
: > ${dir}/elastic/etc/hosts

length=`cat ${dir}/elastic/instances.yml | shyaml get-length instances`
for((i=0;i<${length};i++));
do
  ipString=(`cat ${dir}/elastic/instances.yml | shyaml get-value instances.${i}.ip`)
  dnsString=(`cat ${dir}/elastic/instances.yml | shyaml get-value instances.${i}.dns`)
  ip=${ipString[1]}
  dns=${dnsString[1]}
  echo "${ip}   ${dns}" >> ${dir}/elastic/etc/hosts
done

# 构建容器
docker build \
    --network host \
    -t 15918793994/filebeat:6.2.4 ${dir}/filebeat

# 运行容器
docker run -d --name filebeat --net=host  \
    -v ${dir}/filebeat/certs:/usr/share/filebeat/certs \
    -v ${dir}/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml \
    -v ${dir}/filebeat/logs:/usr/share/filebeat/logs \
    -v ${dir}/filebeat/logs/nginx:/usr/share/filebeat/logs/nginx \
    -v ${dir}/filebeat/prospectors.d:/usr/share/filebeat/prospectors.d \
    -v ${dir}/filebeat/modules.d:/usr/share/filebeat/modules.d \
    -v ${dir}/filebeat/data:/usr/share/filebeat/data \
    -v ${dir}/elastic/etc/hosts:/etc/hosts \
	15918793994/filebeat:6.2.4