#!/bin/bash

dir=$(cd `dirname $0`; pwd)

#############################启动Kibana
# 拉取证书
rm -rf ${dir}/kibana/certs
ln -s ${dir}/elastic/certs ${dir}/kibana/certs

# 删除运行中的容器
docker rm $(docker ps -a| grep "kibana" |cut -d " " -f 1) -f

# 修改项目权限
chown 1000:1000 -R ${dir}/kibana

# 创建容器hosts
: > ${dir}/elastic/etc/hosts

length=`cat ${dir}/elastic/instances.yml | shyaml get-length instances`
for((i=0;i<${length};i++));
do
  ipString=(`cat ${dir}/elastic/instances.yml | shyaml get-value instances.${i}.ip`)
  dnsString=(`cat ${dir}/elastic/instances.yml | shyaml get-value instances.${i}.dns`)
  ip=${ipString[1]}
  dns=${dnsString[1]}
  echo "${ip}   ${dns}" >> ${dir}/elastic/etc/hosts
done

# 拉取公用配置
elasticsearch_url=(`cat ${dir}/elastic/public.yml | shyaml get-value public.elasticsearch.url`)
elasticsearch_username=(`cat ${dir}/elastic/public.yml | shyaml get-value public.elasticsearch.username`)
elasticsearch_password=(`cat ${dir}/elastic/public.yml | shyaml get-value public.elasticsearch.password`)
# 构建容器
docker build \
    --build-arg elasticsearch_url=${elasticsearch_url} \
    --build-arg elasticsearch_username=${elasticsearch_username} \
    --build-arg elasticsearch_password=${elasticsearch_password} \
    --network host \
    -t 15918793994/kibana:6.2.4 ${dir}/kibana

# 运行容器
docker run -d --name kibana --net=host  \
	-v ${dir}/kibana/certs:/usr/share/kibana/certs \
	-v ${dir}/kibana/data:/usr/share/kibana/data \
	-v ${dir}/kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml \
	-v ${dir}/elastic/etc/hosts:/etc/hosts \
	15918793994/kibana:6.2.4