#!/bin/bash

dir=${PWD}

#############################Elastic
docker build --network host -t 15918793994/elasticsearch-rewrite:6.2.4 ${dir}/elastic
docker pull 15918793994/elasticsearch-rewrite:6.2.4
docker rm $(docker ps -a| grep "elastic" |cut -d " " -f 1) -f
docker run --net=host --name elastic -d \
	-v ${dir}/elastic/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml \
	-v ${dir}/elastic/data:/usr/share/elasticsearch/data \
	-v ${dir}/elastic/logs:/usr/share/elasticsearch/logs \
	-e ELASTIC_PASSWORD=123456 \
	15918793994/elasticsearch-rewrite:6.2.4

#############################Kibana
docker pull 15918793994/kibana:6.2.4
docker rm $(docker ps -a| grep "kibana" |cut -d " " -f 1) -f
docker run --net=host --name kibana -d \
	-v ${dir}/kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml \
	15918793994/kibana:6.2.4
