#!/bin/bash

dir=${PWD}

#############################Kibana
docker build --network host -t 15918793994/kibana-rewrite:6.2.4 ${dir}/kibana
docker pull 15918793994/kibana-rewrite:6.2.4
docker rm $(docker ps -a| grep "kibana" |cut -d " " -f 1) -f
docker run --net=host --name kibana -d \
	15918793994/kibana-rewrite:6.2.4
